<?php

namespace Workdo\Hrm\Database\Seeders;

use Illuminate\Database\Seeder;
use Workdo\Hrm\Models\MasterCountryShift;

class MasterCountryShiftSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countryDefaults = [
            [
                'country_name' => 'United States',
                'iso_code' => 'US',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '17:30:00',
                'break_duration_mins' => 30,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'America/New_York',
                'available_timezones' => [
                    'America/New_York',
                    'America/Chicago',
                    'America/Denver',
                    'America/Los_Angeles',
                    'America/Anchorage',
                    'Pacific/Honolulu',
                ],
                'dst_supported' => true,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Bangladesh',
                'iso_code' => 'BD',
                'working_days' => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '18:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Asia/Dhaka',
                'available_timezones' => ['Asia/Dhaka'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'United Kingdom',
                'iso_code' => 'GB',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '17:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 37.50,
                'primary_timezone' => 'Europe/London',
                'available_timezones' => ['Europe/London'],
                'dst_supported' => true,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Canada',
                'iso_code' => 'CA',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '17:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 37.50,
                'primary_timezone' => 'America/Toronto',
                'available_timezones' => [
                    'America/Toronto',
                    'America/Vancouver',
                    'America/Edmonton',
                    'America/Winnipeg',
                    'America/Halifax',
                ],
                'dst_supported' => true,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Australia',
                'iso_code' => 'AU',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '17:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 38.00,
                'primary_timezone' => 'Australia/Sydney',
                'available_timezones' => [
                    'Australia/Sydney',
                    'Australia/Melbourne',
                    'Australia/Brisbane',
                    'Australia/Perth',
                    'Australia/Adelaide',
                ],
                'dst_supported' => true,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Germany',
                'iso_code' => 'DE',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '08:00:00',
                'office_end_time' => '16:30:00',
                'break_duration_mins' => 30,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Europe/Berlin',
                'available_timezones' => ['Europe/Berlin'],
                'dst_supported' => true,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'United Arab Emirates',
                'iso_code' => 'AE',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '07:30:00',
                'office_end_time' => '15:30:00',
                'break_duration_mins' => 30,
                'weekly_working_hours' => 37.50,
                'primary_timezone' => 'Asia/Dubai',
                'available_timezones' => ['Asia/Dubai'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Saudi Arabia',
                'iso_code' => 'SA',
                'working_days' => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
                'office_start_time' => '08:00:00',
                'office_end_time' => '17:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Asia/Riyadh',
                'available_timezones' => ['Asia/Riyadh'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Nigeria',
                'iso_code' => 'NG',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '08:00:00',
                'office_end_time' => '17:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Africa/Lagos',
                'available_timezones' => ['Africa/Lagos'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'India',
                'iso_code' => 'IN',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:30:00',
                'office_end_time' => '18:30:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Asia/Kolkata',
                'available_timezones' => ['Asia/Kolkata'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Singapore',
                'iso_code' => 'SG',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '18:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Asia/Singapore',
                'available_timezones' => ['Asia/Singapore'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
            [
                'country_name' => 'Japan',
                'iso_code' => 'JP',
                'working_days' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                'office_start_time' => '09:00:00',
                'office_end_time' => '18:00:00',
                'break_duration_mins' => 60,
                'weekly_working_hours' => 40.00,
                'primary_timezone' => 'Asia/Tokyo',
                'available_timezones' => ['Asia/Tokyo'],
                'dst_supported' => false,
                'effective_date' => '2026-01-01',
                'version' => 1,
            ],
        ];

        foreach ($countryDefaults as $data) {
            MasterCountryShift::updateOrCreate(
                ['iso_code' => $data['iso_code']],
                $data
            );
        }
    }
}
